name: CenterPivotMatopiba
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - backports
  - backports.functools_lru_cache
  - backports_abc
  - blas
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - click
  - click-plugins
  - cligj
  - curl
  - cycler
  - docutils
  - enum34
  - expat
  - ffmpeg
  - fiona
  - fontconfig
  - freeglut
  - freetype
  - freexl
  - functools32
  - futures
  - gdal
  - geopandas
  - geos
  - giflib
  - glib
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - intel-openmp
  - jasper
  - jpeg
  - json-c
  - kealib
  - kiwisolver
  - krb5
  - libboost
  - libcurl
  - libffi
  - libgdal
  - libkml
  - libnetcdf
  - libopencv
  - libopus
  - libpng
  - libpq
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libxcb
  - libxml2
  - matplotlib
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munch
  - numpy
  - numpy-base
  - opencv
  - openjpeg
  - openssl
  - pandas
  - pcre
  - pip
  - pixman
  - poppler
  - poppler-data
  - proj4
  - py-opencv
  - pyparsing
  - pyproj
  - pyqt
  - python
  - python-dateutil
  - pytz
  - qt
  - rtree
  - scipy
  - setuptools
  - shapely
  - singledispatch
  - sip
  - six
  - sqlite
  - statistics
  - subprocess32
  - tk
  - tornado
  - wheel
  - xerces-c
  - xz
  - zlib
  - zstd
